---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/scrapings/{id}":
    put:
      summary: Update a scraping task
      tags:
      - Scrapings
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Task successfully updated
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                scraped_data:
                  type: string
              required:
              - status
components:
  schemas:
    TaskUpdate:
      type: object
      properties:
        status:
          type: string
        scraped_data:
          type: string
      required:
      - status
    Task:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        description:
          type: string
